(() => {
"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const K={m:"sayeed_memory",a:"sayeed_angle",s:"sayeed_sound",t:"sayeed_theme",h:"sayeed_history",ans:"sayeed_answer",sec:"sayeed_second"};
const E={ex:$("#expression"),res:$("#result"),state:$("#displayState"),mem:$("#memoryText"),keys:$("#keypad"),list:$("#historyList"),search:$("#historySearch"),count:$("#historyCount"),toast:$("#toast")};
let ex="",memory=+(localStorage.getItem(K.m)||0),angle=localStorage.getItem(K.a)==="RAD"?"RAD":"DEG",sound=localStorage.getItem(K.s)!=="off",second=localStorage.getItem(K.sec)==="on",ans=+(localStorage.getItem(K.ans)||0),history=load(),audio=null,filtered=[];
function load(){try{let x=JSON.parse(localStorage.getItem(K.h)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function save(k,v){try{localStorage.setItem(k,String(v))}catch{}}
function savej(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function fmt(v){if(!Number.isFinite(v))throw Error("Math error");if(Math.abs(v)<1e-12)v=0;return Number(v.toPrecision(12)).toString()}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(x){if(!E.toast)return;E.toast.textContent=x;E.toast.classList.add("show");clearTimeout(window.st);window.st=setTimeout(()=>E.toast.classList.remove("show"),1500)}
function beep(type="key"){if(!sound)return;try{const C=AudioContext||webkitAudioContext;audio??=new C();if(audio.state==="suspended")audio.resume();let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.frequency.value=type==="equal"?720:430;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.02,t+.005);g.gain.exponentialRampToValueAtTime(.0001,t+.06);o.connect(g);g.connect(audio.destination);o.start();o.stop(t+.07)}catch{}}
function vib(n=5){try{navigator.vibrate?.(n)}catch{}}
function fact(n){if(!Number.isInteger(n)||n<0||n>170)throw Error("Invalid factorial");let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function rad(v){return angle==="DEG"?v*Math.PI/180:v} function deg(v){return angle==="DEG"?v*180/Math.PI:v}
function fn(n,v){if(n==="sin")return Math.sin(rad(v));if(n==="cos")return Math.cos(rad(v));if(n==="tan"){let r=rad(v);if(Math.abs(Math.cos(r))<1e-12)throw Error("Undefined tangent");return Math.tan(r)}if(n==="asin"){if(v<-1||v>1)throw Error("Domain error");return deg(Math.asin(v))}if(n==="acos"){if(v<-1||v>1)throw Error("Domain error");return deg(Math.acos(v))}if(n==="atan")return deg(Math.atan(v));if(n==="sqrt"){if(v<0)throw Error("Domain error");return Math.sqrt(v)}if(n==="log"){if(v<=0)throw Error("Domain error");return Math.log10(v)}if(n==="ln"){if(v<=0)throw Error("Domain error");return Math.log(v)}if(n==="abs")return Math.abs(v);if(n==="inv"){if(!v)throw Error("Cannot divide by zero");return 1/v}throw Error("Unknown function")}
class P{constructor(s){this.s=s.replace(/×/g,"*").replace(/÷/g,"/").replace(/−/g,"-").replace(/\s/g,"");this.i=0}q(){return this.s[this.i]||""}eat(x){if(this.s.startsWith(x,this.i)){this.i+=x.length;return true}return false}parse(){if(!this.s)return 0;let v=this.add();if(this.i!==this.s.length)throw Error("Invalid expression");return v}add(){let v=this.mul();for(;;){if(this.eat("+"))v+=this.mul();else if(this.eat("-"))v-=this.mul();else return v}}mul(){let v=this.pow();for(;;){if(this.eat("*"))v*=this.pow();else if(this.eat("/")){let d=this.pow();if(!d)throw Error("Cannot divide by zero");v/=d}else return v}}pow(){let v=this.unary();return this.eat("^")?Math.pow(v,this.pow()):v}unary(){if(this.eat("+"))return this.unary();if(this.eat("-"))return-this.unary();return this.post()}post(){let v=this.primary();for(;;){if(this.eat("!"))v=fact(v);else if(this.eat("%"))v/=100;else return v}}primary(){let c=this.q();if(c==="("){this.i++;let v=this.add();if(!this.eat(")"))throw Error("Missing )");return v}if(/[0-9.]/.test(c))return this.num();if(/[A-Za-z_]/.test(c)){let n=this.id();if(n==="PI")return Math.PI;if(n==="E")return Math.E;if(n==="ANS")return ans;if(!this.eat("("))throw Error("Unknown value");let v=this.add();if(!this.eat(")"))throw Error("Missing )");return fn(n,v)}throw Error("Invalid expression")}num(){let s=this.i,d=false;while(/[0-9.]/.test(this.q())){if(this.q()==="."){if(d)break;d=true}this.i++}let v=Number(this.s.slice(s,this.i));if(!Number.isFinite(v))throw Error("Invalid number");return v}id(){let s=this.i;while(/[A-Za-z_]/.test(this.q()))this.i++;return this.s.slice(s,this.i)}}
function calc(x){return new P(x).parse()}
function update(state){E.ex.textContent=ex||"0";E.mem.textContent="M: "+fmt(memory);if(!ex){E.res.textContent="0";E.state.textContent="Ready";return}try{E.res.textContent=fmt(calc(ex));E.state.textContent=state||"Preview"}catch{E.res.textContent="…";E.state.textContent=state||"Editing"}}
function append(v){if(!v)return;if(/(?:[0-9.)%!]|π|e)$/.test(ex)&&/^[0-9.(πeA]/.test(v))ex+="×";if(/^[+×÷]$/.test(v)&&/[+×÷]$/.test(ex))ex=ex.slice(0,-1)+v;else if(v==="−"&&/[+×÷−]$/.test(ex))ex=ex.slice(0,-1)+v;else ex+=v;update()}
function equal(){if(!ex)return;try{let v=calc(ex),r=fmt(v);history.unshift({e:ex,r,t:Date.now()});history=history.slice(0,100);savej(K.h,history);ans=v;save(K.ans,v);ex=r;update("Calculated");render();beep("equal");vib(10)}catch(e){E.res.textContent="Error";E.state.textContent=e.message;beep("error");vib(18)}}
function render(){let q=(E.search.value||"").toLowerCase().trim();filtered=history.filter(x=>!q||(x.e+" "+x.r).toLowerCase().includes(q));E.count.textContent=filtered.length+" calculation"+(filtered.length===1?"":"s");E.list.innerHTML=filtered.length?filtered.map((x,i)=>`<div class="history-item" data-i="${i}"><button class="history-delete" data-del="${i}" type="button">×</button><div class="history-exp">${esc(x.e)}</div><div class="history-result">= ${esc(x.r)}</div></div>`).join(""):'<div class="empty">No calculations yet.</div>'}
function del(i){let x=filtered[i],p=history.indexOf(x);if(p>=0){history.splice(p,1);savej(K.h,history);render();toast("Calculation deleted")}}
E.keys.addEventListener("click",e=>{let b=e.target.closest(".key");if(!b)return;let a=b.dataset.action,v=b.dataset.value,f=b.dataset.fn;b.classList.add("tap");setTimeout(()=>b.classList.remove("tap"),130);if(a==="clear"){ex="";update()}else if(a==="backspace"){ex=ex.slice(0,-1);update()}else if(a==="equals")equal();else if(a==="square"){ex+="^2";update()}else if(a==="cube"){ex+="^3";update()}else if(a==="factorial"){ex+="!";update()}else if(f){let n=second&&["sin","cos","tan"].includes(f)?{sin:"asin(",cos:"acos(",tan:"atan("}[f]:{sin:"sin(",cos:"cos(",tan:"tan(",sqrt:"sqrt(",log:"log(",ln:"ln(",abs:"abs(",inv:"inv("}[f];if(/[0-9.)%!]|π|e$/.test(ex))ex+="×";ex+=n;update()}else if(v){append(v);beep();vib(4)}})
$("#copyBtn").onclick=()=>navigator.clipboard?.writeText(E.res.textContent).then(()=>toast("Result copied")).catch(()=>toast("Copy unavailable"));
$("#degBtn").onclick=()=>{angle="DEG";save(K.a,angle);$("#degBtn").classList.add("active");$("#radBtn").classList.remove("active");update()}
$("#radBtn").onclick=()=>{angle="RAD";save(K.a,angle);$("#radBtn").classList.add("active");$("#degBtn").classList.remove("active");update()}
$("#mcBtn").onclick=()=>{memory=0;save(K.m,memory);update();toast("Memory cleared")};$("#mrBtn").onclick=()=>append(fmt(memory));$("#mPlusBtn").onclick=()=>{try{memory+=(ex?calc(ex):ans);save(K.m,memory);update();toast("Added to memory")}catch{toast("Invalid value")}};$("#mMinusBtn").onclick=()=>{try{memory-=(ex?calc(ex):ans);save(K.m,memory);update();toast("Subtracted from memory")}catch{toast("Invalid value")}}
$("#secondBtn").onclick=()=>{second=!second;save(K.sec,second?"on":"off");$("#secondBtn").classList.toggle("active",second);["sin","cos","tan"].forEach(n=>{let b=$(`[data-fn="${n}"]`);if(b)b.textContent=second?{"sin":"sin⁻¹","cos":"cos⁻¹","tan":"tan⁻¹"}[n]:n})}
$("#soundBtn").onclick=()=>{sound=!sound;save(K.s,sound?"on":"off");$("#soundBtn").textContent=sound?"🔊":"🔇";if(sound)beep()}
$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");save(K.t,document.body.classList.contains("light")?"light":"dark")}
$("#historyBtn").onclick=()=>$("#historySection").scrollIntoView({behavior:"smooth"});
$("#clearHistoryBtn").onclick=()=>{if(history.length&&confirm("Clear all Sayeed calculation history?")){history=[];savej(K.h,history);render();toast("History cleared")}}
$("#exportHistoryBtn").onclick=()=>{if(!history.length)return toast("No history to export");let a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify({app:"Sayeed Calculator",exportedAt:new Date().toISOString(),calculations:history},null,2)],{type:"application/json"}));a.href=u;a.download="sayeed-calculator-history.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
E.search.oninput=render;
E.list.onclick=e=>{let d=e.target.closest("[data-del]");if(d){e.stopPropagation();del(+d.dataset.del);return}let x=e.target.closest(".history-item");if(x){ex=filtered[+x.dataset.i].e;update();toast("Expression restored")}}
document.addEventListener("keydown",e=>{if(/^[0-9.]$/.test(e.key))append(e.key);else if({"+":"+","-":"−","*":"×","/":"÷","%":"%","(":"(",")":")","^":"^"}[e.key])append({"+":"+","-":"−","*":"×","/":"÷","%":"%","(":"(",")":")","^":"^"}[e.key]);else if(e.key==="Enter"||e.key==="=")equal();else if(e.key==="Backspace"){e.preventDefault();ex=ex.slice(0,-1);update()}else if(e.key==="Escape"){ex="";update()}});
if(localStorage.getItem(K.t)==="light")document.body.classList.add("light");
$("#soundBtn").textContent=sound?"🔊":"🔇";if($("#year"))$("#year").textContent=new Date().getFullYear();render();update();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
setTimeout(()=>$("#splash")?.classList.add("hide"),650);
})();
